/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../components/app/AppProvider.vue')['default']
    DialogContent: typeof import('./../components/app/DialogContent.vue')['default']
    IFluentAlert: typeof import('~icons/fluent/alert')['default']
    IFluentAlert48Regular: typeof import('~icons/fluent/alert48-regular')['default']
    IFluentAlertTv48Regular: typeof import('~icons/fluent/alert-tv48-regular')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiAlert: typeof import('~icons/mdi/alert')['default']
    IMdiClose: typeof import('~icons/mdi/close')['default']
    IMdiKeyboardArrowDown: typeof import('~icons/mdi/keyboard-arrow-down')['default']
    IMdiKeyboardArrowUp: typeof import('~icons/mdi/keyboard-arrow-up')['default']
    IMdiMenu: typeof import('~icons/mdi/menu')['default']
    IMdiMenuClose: typeof import('~icons/mdi/menu-close')['default']
    ISolarMapArrowRightBoldDuotone: typeof import('~icons/solar/map-arrow-right-bold-duotone')['default']
    ISvgSpinnersBlocksScale: typeof import('~icons/svg-spinners/blocks-scale')['default']
    LoadingBarContent: typeof import('./../components/app/LoadingBarContent.vue')['default']
    MsgContent: typeof import('./../components/app/MsgContent.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NotificationContent: typeof import('./../components/app/NotificationContent.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NTable: typeof import('naive-ui')['NTable']
    PageCard: typeof import('./../components/pages/PageCard.vue')['default']
    PageSingle: typeof import('./../components/pages/PageSingle.vue')['default']
    PotatoVideo: typeof import('./../components/PotatoVideo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SugonVideo: typeof import('./../components/SugonVideo.vue')['default']
  }
}
